version: '3.8'
services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - ./client/src:/app/src
      - /app/node_modules
    stdin_open: true
    tty: true
    env_file:
      - ./client/.env
    environment:
      - REACT_APP_BACKEND_BASE_ADMIN_URL=localhost:9000
    depends_on:
      - server