export const ROW = [
   { heading: 'Name', id: 1 },
   { heading: 'Email', id: 2 },
   { heading: 'avatar', id: 3 },
   { heading: 'User Id', id: 4 },
   { heading: 'Created By', id: 5 },
   // { heading: 'Private Chat', id: 6 },
   // { heading: 'Online', id: 7 },
   // { heading: 'New Friend Request', id: 8 },
   // { heading: 'Hide User', id: 9 },
   // { heading: 'Account Active', id: 10 },
   // { heading: 'Level', id: 11 },
   // { heading: 'Today Spin', id: 12 },
   { heading: 'Created At', id: 13 },
   // { heading: 'Spin Time Period', id: 14 },
   { heading: 'Updated At', id: 15 },
   { heading: 'Edit', id: 16 },
];
